Service implementation
darenegade/BookNBlock pull request #23
Opened 2018-05-18 13:49 UTC by sikelerd

Ich habe jetzt einfach mal sowohl für Hyperledger als auch Ethereum die Message verschlüsselt.

closes #9 
closes #8 
closes #7

2018-05-22 11:42 UTC, darenegade requested changes

2018-05-22 11:42 UTC, darenegade commented on BookNBlock/src/app/services/transaction.service.ts
> +  insertOffer(doorId: number, prize: number, fromDate: Date, toDate: Date, address: string, name: string, image?: any): Promise<void> {
Das Datenmodell hat sich geändert. Bitte anpassen

2018-05-27 09:00 UTC, sikelerd commented
@darenegade @loelala Könnt ihr euch das bitte anschauen.

2018-05-27 12:31 UTC, darenegade approved these changes

2018-05-27 12:34 UTC, darenegade requested changes

2018-05-27 12:34 UTC, darenegade commented on BookNBlock/src/app/services/transaction.service.ts
> +      id: Math.floor(Math.random() * Number.MAX_SAFE_INTEGER),
Die ID wird vom Contract gesetzt, da der Client nicht weiß, welche ID frei ist.

2018-05-27 12:34 UTC, darenegade commented on BookNBlock/src/app/services/transaction.service.ts
> +      id: Math.floor(Math.random() * Number.MAX_SAFE_INTEGER),
Sonst passt alles 👍

2018-05-28 20:11 UTC, loelala approved these changes

2018-05-29 17:15 UTC, darenegade approved these changes

2018-05-29 17:15 UTC, merged