WIP: Ethereum connector
darenegade/BookNBlock pull request #44
Opened 2018-06-03 14:30 UTC by sikelerd

## Short Description
Erste Implementierung für den Ethereum Connector

## Changes made by this pull request
- Implementierung des Ethereum Connectors
- Smart Contract compilieren und Sourcen dem Client zur Verfügung stellen

## DoD
- [ ] getFreeOffers verwenden
- [ ] Lösung für das Senden finden
- [ ] Tests
- [ ] Doku im Wiki

## Related Issues
closes #11

2018-06-13 09:08 UTC, sikelerd commented
Bis auf die Whisper Sachen funtioniert jetzt alles. Whisper konnte ich noch nicht testen

2018-06-15 14:47 UTC, darenegade commented on BookNBlock/src/app/services/transaction.service.ts
> +      title: ''
Wie ist das jetzt mit dem Titel und dem Namen?

2018-06-17 07:52 UTC, sikelerd commented on BookNBlock/src/app/services/transaction.service.ts
> +      title: ''
Ich hab jetzt den Namen durch Titel ersetzt.

2018-06-19 12:00 UTC, darenegade requested changes
Vielleicht noch die kleinen Verbesserungen, sonst passt es.

2018-06-19 12:00 UTC, darenegade commented on BookNBlock/src/app/connector/ethereum.connector.ts
> +    return this.contract.methods.getOfferIDs().call().then(ids => {
Im Contract wird schon geprüft, dass die ID vorhanden ist. Warum prüfst du es hier nochmal sep.? Mein naiver Ansatz wäre gewesen, direkt das Offer zu holen und wenn en Fehler kommt, dann geb ich ein Feedback an den Nutzer.

2018-06-19 12:00 UTC, darenegade commented on BookNBlock/src/app/connector/ethereum.connector.ts
> +        return 0;
Die ID vom erstellten Offer bekommst du über ein Event, dass vom Contract bei erfolgreicher Erstellung emittiert wird

2018-06-19 16:39 UTC, loelala approved these changes

2018-06-20 15:30 UTC, darenegade approved these changes

2018-06-21 06:54 UTC, merged