Hyperledger Connector mit basisfunktionen
darenegade/BookNBlock pull request #78
Opened 2018-07-03 15:59 UTC by Cotaez

Zusatzfunktionen aufgrund von unterschieden in der Hyperledger Blockchain /den Interfaces nicht umsetzbar

## Short Description
<Inser Desc. here>

## Changes made by this pull request

-
-
-

## DoD

- [ ] Tests
- [ ] Doku im Wiki

## Related Issues
closes #<IssueNr>

2018-07-03 17:07 UTC, darenegade commented
Ich würde mal sagen..... Eine Woche zu spät😂

2018-07-03 21:03 UTC, sikelerd commented on BookNBlock/src/app/connector/hyperledger.connector.ts
> +export class HyperledgerConnector extends BlockchainConnector {
`searchOffer` Methode fehlt.

2018-07-03 21:04 UTC, sikelerd requested changes
Leider kann ich die App dann nicht mehr kompilieren.

2018-07-03 21:04 UTC, sikelerd commented on BookNBlock/src/app/connector/hyperledger.connector.ts
> +    return Promise.resolve({});
Hier muss das Offer zurück gegeben werden.

2018-07-13 13:40 UTC, darenegade commented
Ich schließe den mal, da hier eh nichts mehr passieren wird

2018-07-13 13:40 UTC, closed without merging